#Last Update 2021/08/10
#Hikaru Kimura

import const

#Pin Number
const.LEFT_MOTOR_ENCODER_A_PIN = 7
const.LEFT_MOTOR_ENCODER_B_PIN = 8
const.LEFT_MOTOR_VREF_PIN = 12
const.LEFT_MOTOR_IN1_PIN = 20
const.LEFT_MOTOR_IN2_PIN = 16
const.RIGHT_MOTOR_ENCODER_A_PIN = 26
const.RIGHT_MOTOR_ENCODER_B_PIN = 19
const.RIGHT_MOTOR_VREF_PIN = 13
const.RIGHT_MOTOR_IN1_PIN = 6
const.RIGHT_MOTOR_IN2_PIN = 5
const.SERVOMOTOR_PIN = 25
const.RED_LED_PIN = 9
const.BLUE_LED_PIN = 10
const.GREEN_LED_PIN = 11
const.RELEASING_PIN = 26
const.FLIGHTPIN_PIN = 4

#Variable Threshold
const.ANGLE_THRE = 10
const.SHADOW_EDGE_LENGTH = 15
const.MEASURMENT_INTERVAL = 5
const.MAX_SHADOW_EDGE_LENGTH = 5

#State Threshold
const.PREPARING_GPS_COUNT_THRE= 10
const.PREPARING_TIME_THRE = 10
const.FLYING_FLIGHTPIN_COUNT_THRE = 10
const.DROPPING_ACC_COUNT_THRE = 10
const.DROPPING_ACC_THRE = 1 #加速度の値
const.LANDING_RELEASING_TIME_THRE = 10
const.LANDING_PRE_MOTOR_TIME_THRE = 2
const.STARTING_TIME_THRE = 60
const.MEASURING_SWITCH_COUNT_THRE = 2 #1地点での測位回数
const.MEASURING_MAX_MEASURING_COUNT_THRE = 3